### ISSUE TITLE
500 server error when making creating dataset after update to 2.1.5

### ISSUE THREAD

**Issue by mariespe** [VoSeq/VoSeq#380] opened 2018-01-23 19:34 UTC
After updating to 2.1.5 I get a 500 server error when trying to create datasets. This happens both when creating data from a taxon set and when pasting a voucher code list.

**Comment by carlosp420** [comment] 2018-01-24 04:27
I cannot reproduce the error here.
Maybe there are some error messages in the log.
Can you find any error message in the file `/tmp/voseq_main.debug.log`?

**Comment by mariespe** [comment] 2018-01-24 17:45
No, the log file is empty.

**Comment by carlosp420** [comment] 2018-02-02 14:13
Another log that might be useful is the gunicorn_supervisor.log

Log into your vagrant virtual machine and try to find any "Error" in the gunicorn_supervisor.log. Such file might be found in /home/voseq/logs

I suspect it might be related to #381

**Comment by mariespe** [comment] 2018-02-02 16:20
Yes, when trying to make a dataset the error in #381 shows up in the gunicorn_supervisor.log file

**Comment by carlosp420** [comment] 2018-02-03 17:00
error #381 has been fixed in VoSeq version 2.1.6 but I think it is not related to this issue. Can you upgrade and see if you still get the error?

**Comment by mariespe** [comment] 2018-02-03 18:35
Still can't create a dataset after upgrading, but now I get the following in the gunicorn log file:

[2018-02-03 18:21:42,246] [DEBUG] [MainThread] [public_interface.views] [26] Index
[2018-02-03 18:21:55,017] [ERROR] [MainThread] [django.request] [124] Internal Server Error: /create_dataset/results/
Traceback (most recent call last):
  File "/home/vagrant/.virtualenvs/voseq/lib/python3.4/site-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/home/vagrant/.virtualenvs/voseq/lib/python3.4/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/home/vagrant/.virtualenvs/voseq/lib/python3.4/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/vagrant/.virtualenvs/voseq/lib/python3.4/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/vagrant/.virtualenvs/voseq/lib/python3.4/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/vagrant/voseq/create_dataset/views.py", line 43, in results
    dataset_creator = CreateDataset(form.cleaned_data)
  File "/vagrant/voseq/create_dataset/utils.py", line 83, in __init__
    self.dataset_str = self.create_dataset()
  File "/vagrant/voseq/create_dataset/utils.py", line 107, in create_dataset
    self.create_seq_objs()
  File "/vagrant/voseq/create_dataset/utils.py", line 159, in create_seq_objs
    our_taxon_names, all_seqs)
  File "/vagrant/voseq/create_dataset/utils.py", line 216, in build_seq_obj
    accession_number=accession_number,
TypeError: __init__() got an unexpected keyword argument 'accession_number'

**Comment by carlosp420** [comment] 2018-02-03 19:10
version 2.1.5 uses newer version of some dependencies.

can you make sure that you have the latest required dependencies?

log into vagrant and install them:

```
vagrant ssh
cd /vagrant
workon voseq
pip install -r requirements/base.txt
```
and then try to create a dataset?

**Comment by mariespe** [comment] 2018-02-03 19:21
That did it. Thanks!

**Closed** 2018-02-03 19:22 UTC
